# This function creates a special "matrix" object 
# that can cache its inverse.

makeCacheMatrix <- function(x = matrix()) {
  inversematrix <- NULL # initialize
  set <- function(y) { # if called, store in cache the matrix and inversed matrix initialisation
    x <<- y
    inversematrix <<- NULL
  }
  get <- function() x # if called, return the matrix 
  setinverse <- function(inv) inversematrix <<- inv # set the newly computed inverse in cache
  getinverse <- function() inversematrix # get the inverse, if need not be computed again
  list(set = set, get = get,
       setinverse = setinverse,
       getinverse = getinverse) # return the list of objects
}


# This function computes the inverse of the special "matrix" returned by makeCacheMatrix above.
# function will take a cache object generated by the makecache function

cacheSolve <- function(x, ...) {
  ## Return a matrix that is the inverse of 'x'
  inversematrix <- x$getinverse() # first attempt to check if in cache
  if(!is.null(inversematrix)) { # if yes proceed
    message("getting cached data")
    return(inversematrix)
  }
  data <- x$get() # get the init matrix
  inversematrix <- solve(data, ...) # inbuilt
  x$setinverse(inversematrix) # pass result to cache
  inversematrix
}
